#      __                      __  ___
#     / /   ____  ____  ____ _/  |/  /__  ____ ___  ____  _______  __
#    / /   / __ \/ __ \/ __ `/ /|_/ / _ \/ __ `__ \/ __ \/ ___/ / / /
#   / /___/ /_/ / / / / /_/ / /  / /  __/ / / / / / /_/ / /  / /_/ /
#  /_____/\____/_/ /_/\__, /_/  /_/\___/_/ /_/ /_/\____/_/   \__, /
#                      /____/                                 /____/
#
#  cavira oss (c) 2026  -  nullure (c) 2026
#  ----------------------------------------------------------
#  file  : .github/workflows/main.yml
#  usage : automates the LongMemory main workflow

name: Update contributors

on:
    push:
        branches:
            - main

jobs:
    contrib-readme-job:
        if: github.repository == 'CaviraOSS/LongMemory'
        runs-on: ubuntu-latest
        name: A job to automate contrib in readme
        permissions:
            contents: write
            pull-requests: write
        steps:
            - name: Contribute List
              uses: akhilmhdh/contributors-readme-action@v2.3.11
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
